FROM nexus.engageska-portugal.pt/ska-docker/ska-python-buildenv:latest AS buildenv
FROM nexus.engageska-portugal.pt/ska-docker/ska-python-runtime:latest AS runtime

ENTRYPOINT ["python", "SDPSubarray"]
CMD ["1", "-v4"]
