FROM nexus.engageska-portugal.pt/sdp-prototype/pytango_ska_dev:latest
USER root 
RUN pip3 install jsonschema
RUN pip3 install lmcbaseclasses==0.5.1 --index-url https://nexus.engageska-portugal.pt/repository/pypi/simple
